# Generated by Django 2.1.8 on 2020-11-13 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_title', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶名字')),
                ('bottle_content', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='发车时间')),
                ('status', models.CharField(choices=[(0, '草稿'), (1, '已投放'), (2, '已捞起'), (3, '已回复')], max_length=1, verbose_name='状态')),
                ('delete', models.BooleanField(default=0, verbose_name='是否可以删除')),
            ],
            options={
                'verbose_name_plural': '漂流瓶',
                'verbose_name': '漂流瓶',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_title', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶名字')),
                ('bottle_content', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('add_date', models.DateField(auto_now=True, verbose_name='创建日期')),
                ('bottle', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Bottle', verbose_name='漂流瓶')),
            ],
            options={
                'verbose_name_plural': '漂流瓶',
                'verbose_name': '漂流瓶',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('nick_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='昵称')),
                ('gender', models.BooleanField(default=1, verbose_name='性别')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='邮箱')),
                ('address', models.TextField(blank=True, null=True, verbose_name='地址')),
                ('image', models.ImageField(default='upload/user/!happy-face.png', upload_to='upload/user', verbose_name='用户头像')),
            ],
            options={
                'verbose_name_plural': '普通用户',
                'verbose_name': '普通用户',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='评论人'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='发送者'),
        ),
    ]
