# Generated by Django 2.1.8 on 2020-11-14 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle_title', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶名字')),
                ('bottle_content', models.CharField(max_length=30, unique=True, verbose_name='漂流瓶内容')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('add_date', models.DateField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '捞起记录',
                'verbose_name_plural': '捞起记录',
            },
        ),
        migrations.AddField(
            model_name='bottle',
            name='pick_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='pick_user', to='home.User', verbose_name='捞起人'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='add_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='status',
            field=models.CharField(choices=[(0, '未投放'), (1, '已投放'), (2, '已捞起'), (3, '已回复')], max_length=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='send_user', to='home.User', verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='pickrecords',
            name='bottle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Bottle', verbose_name='漂流瓶'),
        ),
        migrations.AddField(
            model_name='pickrecords',
            name='comment_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='评论人'),
        ),
    ]
