# Generated by Django 2.1.8 on 2020-11-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201114_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='add_date',
        ),
        migrations.AddField(
            model_name='bottle',
            name='add_date',
            field=models.DateField(auto_now=True, verbose_name='创建日期'),
        ),
    ]
