# Generated by Django 2.1.8 on 2020-11-14 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20201114_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='pick_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pick_user', to='home.User', verbose_name='捞起人'),
        ),
    ]
