# Generated by Django 2.1.8 on 2020-11-14 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_bottle_launch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='pick_up_time',
            field=models.DateTimeField(null=True, verbose_name='捞起时间'),
        ),
    ]
