# Generated by Django 2.1.8 on 2020-11-14 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_bottle_pick_up_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='reply_status',
            field=models.BooleanField(default=0, verbose_name='是否回复'),
        ),
    ]
