# Generated by Django 2.1.8 on 2020-11-14 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_bottle_reply_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickrecords',
            name='add_time',
        ),
        migrations.RemoveField(
            model_name='pickrecords',
            name='bottle_content',
        ),
        migrations.RemoveField(
            model_name='pickrecords',
            name='bottle_title',
        ),
        migrations.RemoveField(
            model_name='pickrecords',
            name='comment_user',
        ),
        migrations.AddField(
            model_name='pickrecords',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.User', verbose_name='捞起人'),
        ),
        migrations.AlterField(
            model_name='pickrecords',
            name='add_date',
            field=models.DateField(auto_now=True, verbose_name='捞起日期'),
        ),
    ]
